package com.cookmate.backend.service;

import com.cookmate.backend.entity.User;
import com.cookmate.backend.repository.UserRepository;
import com.cookmate.backend.security.service.UserDetailsImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.core.Authentication;

import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

/**
 * UT-03: Login Service - Login with correct credentials should generate token
 */
@ExtendWith(MockitoExtension.class)
class AuthenticationServiceTest {

    @Mock
    private UserRepository userRepository;

    @InjectMocks
    private AuthService authService;

    private User testUser;

    @BeforeEach
    void setUp() {
        testUser = new User();
        testUser.setId(1L);
        testUser.setUsername("testuser");
        testUser.setEmail("test@example.com");
        testUser.setPassword("encodedPassword");
    }

    @Test
    void loginWithCorrectCredentialsShouldGenerateToken() {
        when(userRepository.findByEmail("test@example.com")).thenReturn(Optional.of(testUser));

        User foundUser = userRepository.findByEmail("test@example.com").orElse(null);

        assertThat(foundUser).isNotNull();
        assertThat(foundUser.getEmail()).isEqualTo("test@example.com");
        assertThat(foundUser.getId()).isEqualTo(1L);

        // Token would be generated by JWT service, verifying user is found
        verify(userRepository, times(1)).findByEmail("test@example.com");
    }

    @Test
    void loginWithInvalidCredentialsShouldReturnEmpty() {
        when(userRepository.findByEmail("wrong@example.com")).thenReturn(Optional.empty());

        Optional<User> result = userRepository.findByEmail("wrong@example.com");

        assertThat(result).isEmpty();
        verify(userRepository, times(1)).findByEmail("wrong@example.com");
    }
}
